Repository googleapis/java-cloudbuild, pull requests merged in 2020-09, with the labels that each got.

#240 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudbuild, cla: yes, context: full

#242 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#246 feat: add dynamic_substitutions to BuildOptions, STACKDRIVER_ONLY/CLOUD_LOGGING_ONLY to LoggingMode, name/service_account to Build
  README.md
  google-cloud-build/src/main/java/com/google/cloud/devtools/cloudbuild/v1/stub/GrpcCloudBuildStub.java
  google-cloud-build/src/test/java/com/google/cloud/devtools/cloudbuild/v1/CloudBuildClientTest.java
  proto-google-cloud-build-v1/pom.xml
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Artifacts.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Build.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildName.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildOptions.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildOptionsOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildStep.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildStepOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildTrigger.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildTriggerName.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildTriggerOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/CancelBuildRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/CancelBuildRequestOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Cloudbuild.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/CreateBuildRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/CreateBuildRequestOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/GetBuildRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/GetBuildRequestOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/ListBuildsRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/ListBuildsRequestOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/LocationName.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/ProjectName.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/PullRequestFilter.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/PullRequestFilterOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/RetryBuildRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/RetryBuildRequestOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/ServiceAccountName.java
  proto-google-cloud-build-v1/src/main/proto/google/devtools/cloudbuild/v1/cloudbuild.proto
  synth.metadata
Labels: automerge, cla: yes, context: partial

#257 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#259 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#260 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: cloudbuild, automerge, cla: yes

#267 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#269 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
