Repository googleapis/java-cloudbuild, pull requests merged in 2020-06, with the labels that each got.

#171 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#172 chore: regenerate with updated protoc
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/ArtifactResult.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Artifacts.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Build.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildOperationMetadata.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildOptions.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildStep.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuildTrigger.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/BuiltImage.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/CancelBuildRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/CreateBuildRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/CreateBuildTriggerRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/CreateWorkerPoolRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/DeleteBuildTriggerRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/DeleteWorkerPoolRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/FileHashes.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/GetBuildRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/GetBuildTriggerRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/GetWorkerPoolRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/GitHubEventsConfig.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Hash.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/ListBuildTriggersRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/ListBuildTriggersResponse.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/ListBuildsRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/ListBuildsResponse.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/ListWorkerPoolsRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/ListWorkerPoolsResponse.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Network.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/PullRequestFilter.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/PushFilter.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/RepoSource.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Results.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/RetryBuildRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/RunBuildTriggerRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Secret.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Source.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/SourceProvenance.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/StorageSource.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/TimeSpan.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/UpdateBuildTriggerRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/UpdateWorkerPoolRequest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Volume.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/WorkerConfig.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/WorkerPool.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#174 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#176 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#178 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#183 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#187 ci: switch to secret manager for samples/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#188 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-build/pom.xml
  grpc-google-cloud-build-v1/pom.xml
  pom.xml
  proto-google-cloud-build-v1/pom.xml
Labels: cla: yes

#192 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#195 chore: set Ruby namespace in proto options
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Cloudbuild.java
  proto-google-cloud-build-v1/src/main/proto/google/devtools/cloudbuild/v1/cloudbuild.proto
  synth.metadata
Labels: cla: yes, context: full

#204 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
