Repository googleapis/java-cloudbuild, pull requests merged in 2020-12, with the labels that each got.

#344 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: full

#346 chore: Update CODEOWNERS
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: cloudbuild, cla: yes

#347 chore: Update Code Owners
  .github/CODEOWNERS
  synth.metadata
Labels: api: cloudbuild, cla: yes, context: none

#349 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes

#350 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes

#354 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes

#361 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes

#362 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: full

#363 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: full, merge
