Repository googleapis/java-cloudbuild, pull requests merged in 2021-05, with the labels that each got.

#471 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: none

#472 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudbuild, automerge, cla: yes

#474 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudbuild, cla: yes, context: full

#473 feat: Implementation of Source Manifests: - Added message StorageSourceManifest as an option for the Source message - Added StorageSourceManifest field to the SourceProvenance message
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Cloudbuild.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/Source.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/SourceOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/SourceProvenance.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/SourceProvenanceOrBuilder.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/StorageSourceManifest.java
  proto-google-cloud-build-v1/src/main/java/com/google/cloudbuild/v1/StorageSourceManifestOrBuilder.java
  proto-google-cloud-build-v1/src/main/proto/google/devtools/cloudbuild/v1/cloudbuild.proto
  synth.metadata
Labels: api: cloudbuild, cla: yes, context: full

#478 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes

#479 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes

#480 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: full

#484 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes

#486 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes

#485 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: full

#488 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: full

#492 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: full

#493 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes

#497 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes
