Repository googleapis/java-cloudbuild, pull requests merged in 2021-06, with the labels that each got.

#507 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes

#508 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes

#500 chore: release gapic-generator-java v1.0.10
  google-cloud-build/src/test/java/com/google/cloud/devtools/cloudbuild/v1/CloudBuildClientTest.java
  synth.metadata
Labels: api: cloudbuild, cla: yes, context: full

#509 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  google-cloud-build-bom/pom.xml
  google-cloud-build/pom.xml
  google-cloud-build/src/main/java/com/google/cloud/devtools/cloudbuild/v1/stub/CloudBuildStubSettings.java
  google-cloud-build/src/test/java/com/google/cloud/devtools/cloudbuild/v1/CloudBuildClientTest.java
  owlbot.py
  pom.xml
  synth.py
  versions.txt
Labels: api: cloudbuild, automerge, cla: yes, owlbot:run

#520 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbuild, automerge, cla: yes
